---
host: localhost
scheme: 'http'
servers:
  - name: Server A
    scheme: http
    host: cp-1
    port: 1111
  - name: Server B
    scheme: http
    host: cp-2
    port: 2222
  - name: Server C
    scheme: http
    host: cp-3
    port: 3333
